/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2018-03-08 11:10:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class message_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/java_web_pro/yklgbbs/code/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/yklgbbs/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1517388735640L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>我的消息</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("  <meta name=\"keywords\" content=\"fly,layui,前端社区\">\r\n");
      out.write("  <meta name=\"description\" content=\"Fly社区是模块化前端UI框架Layui的官网社区，致力于为web开发提供强劲动力\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../res/layui/css/layui.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../res/css/global.css\">\r\n");
      out.write("  \r\n");
      out.write("    <!-- 首先需要引入css样式表 与 js -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/css/mricode.pagination.css\" rel=\"stylesheet\" type=\"text/css\" charset=\"utf-8\">\r\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/js/mricode.pagination.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/js/template-web.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \t<script type=\"text/javascript\">\r\n");
      out.write("  \t\twindow.onload=function(){\r\n");
      out.write("\t\t\t//这里就是ajax生成局部页面的内容\r\n");
      out.write("\t\t\t//1：给我的消息进行分页\r\n");
      out.write("\t\t\t$(\"#page_message\").pagination({ \r\n");
      out.write("\t\t\t\tpageIndex:0, //从pageIndex+1页开始显示（重要）\r\n");
      out.write("\t\t\t\tpageSize:10, //分页后每页显示10条数据\r\n");
      out.write("\t\t\t\tpageBtnCount:9, //按钮个数，包括上下页，首尾页\r\n");
      out.write("\t\t\t\tshowFirstLastBtn:true, //是否显示首页，尾页按钮\r\n");
      out.write("\t\t\t\tfirstBtnText:\"首页\", //这里可以设置个性显示内容\r\n");
      out.write("\t\t\t\tlastBtnText:\"尾页\",\r\n");
      out.write("\t\t\t\tprevBtnText:\"上一页\",\r\n");
      out.write("\t\t\t\tnextBtnText:\"下一页\",\r\n");
      out.write("\t\t\t\tremote:{\r\n");
      out.write("\t\t\t\t\t//每次点击按钮提交到处理请求的Servlet\r\n");
      out.write("\t\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ajaxMessage.do', \r\n");
      out.write("\t\t\t\t\tsuccess:function(data){ //注：data为：json字符串通过转换为了json对象\r\n");
      out.write("\t\t\t\t\t\tvar html=template('mdl_message',data); //date渲染到test模板中\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('myMessage').innerHTML=html;\r\n");
      out.write("\t\t\t\t\t\tvar OMessage=document.getElementById('myMessage');\r\n");
      out.write("\t\t\t\t\t\tvar ALi=OMessage.getElementsByTagName('li');\r\n");
      out.write("\t\t\t\t\t\tif(ALi.length!=0){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('delete_all').style.display='block';\r\n");
      out.write("\t\t\t\t\t\t\tforeachDeleteMessage();\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('no_message').style.display='block';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction foreachDeleteMessage(){\r\n");
      out.write("\t\t\t\t//遍历删除单个消息事件\r\n");
      out.write("\t\t\t\tvar ADeleteOne=document.getElementsByClassName('delete_one');\r\n");
      out.write("\t\t\t\tfor(var i=0;i<ADeleteOne.length;i++){\r\n");
      out.write("\t\t\t\t\tADeleteOne[i].onclick=deleteOneMessageAjax;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//删除单个消息\r\n");
      out.write("            function  deleteOneMessageAjax(){\r\n");
      out.write("            \tif(confirm('确定删除该消息吗？')==false){\r\n");
      out.write("            \t\treturn;\r\n");
      out.write("            \t}\r\n");
      out.write("                //获取评论id\r\n");
      out.write("                var messageid=this.getElementsByTagName('input')[0].value;\r\n");
      out.write("                //创建ajax对象\r\n");
      out.write("                var xhr=new XMLHttpRequest();\r\n");
      out.write("                //连接服务器\r\n");
      out.write("                xhr.open(\"get\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("//deleteMessage.do?req=\"+messageid,true);\r\n");
      out.write("                //发送\r\n");
      out.write("                xhr.send();\r\n");
      out.write("                //响应\r\n");
      out.write("                xhr.onreadystatechange=function () {\r\n");
      out.write("                    if(xhr.readyState===4){\r\n");
      out.write("                        if(xhr.status===200){\r\n");
      out.write("                            var temp=xhr.responseText;\r\n");
      out.write("                            if(temp=='true'){\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('li_'+messageid).style.display='none';\r\n");
      out.write("                            }else{\r\n");
      out.write("                                alert(\"呀！删除失败了\");\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//删除全部消息\r\n");
      out.write("\t\t\tvar delete_all=document.getElementById('delete_all');\r\n");
      out.write("\t\t\tdelete_all.onclick=function () {\r\n");
      out.write("            \tif(confirm('确定清空全部消息吗？')==false){\r\n");
      out.write("            \t\treturn;\r\n");
      out.write("            \t}\r\n");
      out.write("                //创建ajax对象\r\n");
      out.write("                var xhr=new XMLHttpRequest();\r\n");
      out.write("                //连接服务器\r\n");
      out.write("                xhr.open(\"get\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("//deleteMessage.do?req=all\",true);\r\n");
      out.write("                //发送\r\n");
      out.write("                xhr.send();\r\n");
      out.write("                //响应\r\n");
      out.write("                xhr.onreadystatechange=function () {\r\n");
      out.write("                    if(xhr.readyState===4){\r\n");
      out.write("                        if(xhr.status===200){\r\n");
      out.write("                            var temp=xhr.responseText;\r\n");
      out.write("                            if(temp=='true'){\r\n");
      out.write("                            \twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/user/message.jsp\";\r\n");
      out.write("                            }else{\r\n");
      out.write("                                alert(\"呀！清空失败了\");\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<script id=\"mdl_message\" type=\"text/html\">\r\n");
      out.write("\t  {{ each list as messageEx}}\r\n");
      out.write("          <li id=\"li_{{messageEx.id}}\">\r\n");
      out.write("            <blockquote class=\"layui-elem-quote\">\r\n");
      out.write("              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home/{{messageEx.userid}}\" target=\"_blank\"><cite>{{messageEx.nickname}}</cite></a>回答了您的求解<a target=\"_blank\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/topicDetail.do?topicid={{messageEx.topicid}}");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'#'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("{{messageEx.commentid}}\"><cite>{{messageEx.title}}</cite></a>\r\n");
      out.write("            </blockquote>\r\n");
      out.write("            <p><span>{{messageEx.commentTime}}</span><a href=\"javascript:;\" class=\"delete_one layui-btn layui-btn-small layui-btn-danger\">删除<input type=\"hidden\" value=\"{{messageEx.id}}\"/></a></p>\r\n");
      out.write("          </li>\r\n");
      out.write("\t  {{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("  <div class=\"main\">\r\n");
      out.write("    <a class=\"logo\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goIndex/all\" title=\"Fly\">Fly社区</a>\r\n");
      out.write("    <div class=\"nav\">\r\n");
      out.write("      <a class=\"nav-this\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goIndex/all\">\r\n");
      out.write("        <i class=\"iconfont icon-wenda\"></i>问答\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"http://www.layui.com/\" target=\"_blank\">\r\n");
      out.write("        <i class=\"iconfont icon-ui\"></i>框架\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"nav-user\">      \r\n");
      out.write("      <!-- 登入后的状态 -->\r\n");
      out.write("      \r\n");
      out.write("      <a class=\"avatar\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/user/center.jsp\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.headUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("        <cite>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</cite>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a style=\"display:inline-block; position:relative; top:-1px\" class=\"avatar\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/grade_list.jsp\"><i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.grade }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</i> </a>\r\n");
      out.write("      <div class=\"nav\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/user/set.jsp\"><i class=\"iconfont icon-shezhi\"></i>设置</a>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout.do\"><i class=\"iconfont icon-tuichu\" style=\"top: 0; font-size: 22px;\"></i>退了</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main fly-user-main layui-clear\">\r\n");
      out.write("  <ul class=\"layui-nav layui-nav-tree layui-inline\" lay-filter=\"user\">\r\n");
      out.write("    <li class=\"layui-nav-item\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("        <i class=\"layui-icon\">&#xe609;</i>\r\n");
      out.write("        我的主页\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"layui-nav-item\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/user/center.jsp\">\r\n");
      out.write("        <i class=\"layui-icon\">&#xe612;</i>\r\n");
      out.write("        用户中心\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"layui-nav-item\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/user/set.jsp\">\r\n");
      out.write("        <i class=\"layui-icon\">&#xe620;</i>\r\n");
      out.write("        基本设置\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"layui-nav-item layui-this\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/user/message.jsp\">\r\n");
      out.write("        <i class=\"layui-icon\">&#xe611;</i>\r\n");
      out.write("        我的消息\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"site-tree-mobile layui-hide\">\r\n");
      out.write("    <i class=\"layui-icon\">&#xe602;</i>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"site-mobile-shade\"></div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"fly-panel fly-panel-user\" pad20>\r\n");
      out.write("\t  <div class=\"layui-tab layui-tab-brief\" lay-filter=\"user\" id=\"LAY_msg\" style=\"margin-top: 15px;\">\r\n");
      out.write("\t    <!-- <button class=\"layui-btn layui-btn-danger\" id=\"LAY_delallmsg\">清空全部消息</button> -->\r\n");
      out.write("\t    <button style=\"display:none;\" class=\"layui-btn layui-btn-danger\" id=\"delete_all\">清空全部消息</button>\r\n");
      out.write("\t    <div style=\"display:none;font-size:20px;\" id=\"no_message\" class=\"fly-none\">呀！还没有任何消息</div>\r\n");
      out.write("\t    <div  id=\"LAY_minemsg\" style=\"margin-top: 10px;\">\r\n");
      out.write("        <!--<div class=\"fly-none\">您暂时没有最新消息</div>-->\r\n");
      out.write("        <ul id=\"myMessage\" class=\"mine-msg\">\r\n");
      out.write("<!--           <li data-id=\"123\">\r\n");
      out.write("            <blockquote class=\"layui-elem-quote\">\r\n");
      out.write("              <a href=\"/jump?username=Absolutely\" target=\"_blank\"><cite>Absolutely</cite></a>回答了您的求解<a target=\"_blank\" href=\"/jie/8153.html/page/0/#item-1489505778669\"><cite>layui后台框架</cite></a>\r\n");
      out.write("            </blockquote>\r\n");
      out.write("            <p><span>1小时前</span><a href=\"javascript:;\" class=\"layui-btn layui-btn-small layui-btn-danger fly-delete\">删除</a></p>\r\n");
      out.write("          </li> -->\r\n");
      out.write("<!--           <li data-id=\"123\">\r\n");
      out.write("            <blockquote class=\"layui-elem-quote\">\r\n");
      out.write("              系统消息：欢迎使用 layui\r\n");
      out.write("            </blockquote>\r\n");
      out.write("            <p><span>1小时前</span><a href=\"javascript:;\" class=\"layui-btn layui-btn-small layui-btn-danger fly-delete\">删除</a></p>\r\n");
      out.write("          </li> -->\r\n");
      out.write("        </ul>\r\n");
      out.write("      <!-- 分页页码  下面的class去掉貌似也没什么问题-->\r\n");
      out.write("\t  <div id=\"page_message\" class=\"m-pagination\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("  <p><a href=\"http://fly.layui.com/\">Fly社区</a> 2017 &copy; <a href=\"http://www.layui.com/\">layui.com</a></p>\r\n");
      out.write("  <p>\r\n");
      out.write("    <a href=\"http://fly.layui.com/auth/get\" target=\"_blank\">产品授权</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/8157.html\" target=\"_blank\">获取Fly社区模版</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/2461.html\" target=\"_blank\">微信公众号</a>\r\n");
      out.write("  </p>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"../../res/layui/layui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("layui.cache.page = 'user';\r\n");
      out.write("layui.cache.user = {\r\n");
      out.write("  username: '游客'\r\n");
      out.write("  ,uid: -1\r\n");
      out.write("  ,avatar: '../../res/images/avatar/00.jpg'\r\n");
      out.write("  ,experience: 83\r\n");
      out.write("  ,sex: '男'\r\n");
      out.write("};\r\n");
      out.write("layui.config({\r\n");
      out.write("  version: \"2.0.0\"\r\n");
      out.write("  ,base: '../../res/mods/'\r\n");
      out.write("}).extend({\r\n");
      out.write("  fly: 'index'\r\n");
      out.write("}).use('fly');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /jsp/user/message.jsp(6,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write('\r');
        out.write('\n');
        out.write('	');
        if (_jspx_meth_c_005fredirect_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write('\r');
        out.write('\n');
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f0 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    _jspx_th_c_005fredirect_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fredirect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /jsp/user/message.jsp(7,1) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fredirect_005f0.setUrl("/jsp/login.jsp");
    int _jspx_eval_c_005fredirect_005f0 = _jspx_th_c_005fredirect_005f0.doStartTag();
    if (_jspx_th_c_005fredirect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f0);
    return false;
  }
}
