/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2018-03-08 11:00:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import com.neusoft.utils.TimeToStringUtil;
import com.neusoft.bean.Userinfo;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/java_web_pro/yklgbbs/code/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/yklgbbs/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1517388735640L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.neusoft.utils.TimeToStringUtil");
    _jspx_imports_classes.add("com.neusoft.bean.Userinfo");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 这个判断就没什么必要了 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   \t\t\t\t -->\r\n");
      out.write("   \t\t\t\t<!-- 重点：如果是上面这样写的话判断的是list的长度，\r\n");
      out.write("   \t\t\t\t\t\t       实际上只需判断list是否为null即可。\r\n");
      out.write("   \t\t\t\t\t\t      如果用empty 当帖子长度为0时，就会进入死循环。\r\n");
      out.write("   \t\t\t\t -->\r\n");
      out.write("   \t\t\t\t\r\n");
      out.write("\t\t      \t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\t\t      \t\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>基于 layui 的极简社区页面模版</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("  <meta name=\"keywords\" content=\"fly,layui,前端社区\">\r\n");
      out.write("  <meta name=\"description\" content=\"Fly社区是模块化前端UI框架Layui的官网社区，致力于为web开发提供强劲动力\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/layui/css/layui.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/css/global.css\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- 为编辑和删除帖子设置效果 -->\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("        .top_good_form{\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        .delete_topic,.editor_topic{\r\n");
      out.write("            color: black;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .delete_topic:hover,.editor_topic:hover{\r\n");
      out.write("            color: #3bc3e0;\r\n");
      out.write("            transition: 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .fly-list-li{\r\n");
      out.write("        \tposition: relative;\r\n");
      out.write("        }\r\n");
      out.write("                #sign_d1{\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 38px;\r\n");
      out.write("            background-color: #f97044;\r\n");
      out.write("            color: white;\r\n");
      out.write("            line-height: 38px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* \r\n");
      out.write("        \t签到设置样式\r\n");
      out.write("         */\r\n");
      out.write("        #sign_d1:hover{\r\n");
      out.write("        \tborder-radius: 0;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            color: snow;\r\n");
      out.write("            background-color: #ff5722;\r\n");
      out.write("            transition: 0.8s;\r\n");
      out.write("        }\r\n");
      out.write("        #sign_d2{\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 38px;\r\n");
      out.write("            background-color: #fbf8f8;\r\n");
      out.write("            border: 1px #e6e6e6 solid;\r\n");
      out.write("            color: darkgray;\r\n");
      out.write("            line-height: 38px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        #sign_d2:hover{\r\n");
      out.write("            cursor: not-allowed;\r\n");
      out.write("        }\r\n");
      out.write("   </style>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  <script type=\"text/javascript\" charset=\"utf-8\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/js/template-web.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("        window.onload=function(){\r\n");
      out.write("        \t//将json字符串渲染到指定模板中\r\n");
      out.write("        \t//1：本周top回答渲染 与 将weekAnswerList存入cookie\r\n");
      out.write("        \tvar str1='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.weekAnswerList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'; //此时的str1为字符串\r\n");
      out.write("        \tdocument.cookie='weekAnswerList='+str1+';Path=/';\r\n");
      out.write("        \tvar json1=JSON.parse(str1);\r\n");
      out.write("\t\t\tvar html1=template('wal',json1);\r\n");
      out.write("\t\t\tdocument.getElementById('weekAnswerTop').innerHTML=html1;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//2：飞吻数前8榜渲染 与 将hotViewList存入cookie\r\n");
      out.write("\t\t\tvar str2='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.kissNumList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'; //此时的str2为字符串\r\n");
      out.write("        \tdocument.cookie='kissNumList='+str2+';Path=/';\r\n");
      out.write("\t\t\tvar json2=JSON.parse(str2);\r\n");
      out.write("\t\t\tvar html2=template('knl',json2);\r\n");
      out.write("\t\t\tdocument.getElementById('kissNumList').innerHTML=html2;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//3：10天内热视渲染 与 将hotViewList存入cookie\r\n");
      out.write("\t\t\tvar str3='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.hotViewList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'; //此时的str3为字符串\r\n");
      out.write("        \tdocument.cookie='hotViewList='+str3+';Path=/';\r\n");
      out.write("\t\t\tvar json3=JSON.parse(str3);\r\n");
      out.write("\t\t\tvar html3=template('hvl',json3);\r\n");
      out.write("\t\t\tdocument.getElementById('hotViewList').innerHTML+=html3;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//4：10天内热答渲染 与 将hotReplyList存入cookie\r\n");
      out.write("        \tvar str4='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.hotReplyList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'; //此时的str4为字符串\r\n");
      out.write("        \tdocument.cookie='hotReplyList='+str4+';Path=/';\r\n");
      out.write("\t\t\tvar json4=JSON.parse(str4);\r\n");
      out.write("\t\t\tvar html4=template('hrl',json4);\r\n");
      out.write("\t\t\tdocument.getElementById('hotReplyList').innerHTML+=html4;\r\n");
      out.write("\t\t\t\r\n");
      out.write("        \t\r\n");
      out.write("        \t//为编辑帖子设置点击事件\r\n");
      out.write("\t\t\tvar AEditor=document.getElementsByClassName('editor_topic');\r\n");
      out.write("            var ATopGoodForm=document.getElementsByClassName('top_good_form');\r\n");
      out.write("\r\n");
      out.write("            for(var i=0;i<AEditor.length;i++){\r\n");
      out.write("                AEditor[i].showForm=i;\r\n");
      out.write("                AEditor[i].OnOff=false;\r\n");
      out.write("                AEditor[i].onclick=function () {\r\n");
      out.write("                    if(this.OnOff===false){\r\n");
      out.write("                        ATopGoodForm[this.showForm].style.display='inline-block';\r\n");
      out.write("                    }else{\r\n");
      out.write("                        ATopGoodForm[this.showForm].style.display='none';\r\n");
      out.write("                    }\r\n");
      out.write("                    this.OnOff=!this.OnOff;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        \tvar OMoreTopic=document.getElementById('moreTopic');\r\n");
      out.write("\t\t\tif(OMoreTopic!=null){\r\n");
      out.write("\t            OMoreTopic.onclick=function () {\r\n");
      out.write("\t                document.cookie='pageNum=1;Path=/';  //功能为每次点击 更多求解 都从第2页开始，有时不是很人性化，就取消了,然后又注回来了^_^\r\n");
      out.write("\t            }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("            \r\n");
      out.write("          //获取js中的cookie的方法（这个不是自己写的哦！）\r\n");
      out.write(" \t\t\tfunction get_cookie(Name) {\r\n");
      out.write("\t\t\t\tvar search = Name + \"=\"//查询检索的值\r\n");
      out.write("\t\t\t\tvar returnvalue = \"\";//返回值\r\n");
      out.write("\t\t\t\tif (document.cookie.length > 0) {\r\n");
      out.write("\t\t\t\tsd = document.cookie.indexOf(search);\r\n");
      out.write("\t\t\t\t\tif (sd!= -1) {\r\n");
      out.write("\t\t\t\t\tsd += search.length;\r\n");
      out.write("\t\t\t\t\tend = document.cookie.indexOf(\";\", sd);\r\n");
      out.write("\t\t\t\t\tif (end == -1)\r\n");
      out.write("\t\t\t\t\tend = document.cookie.length;\r\n");
      out.write("\t\t\t    \t//unescape() 函数可对通过 escape() 编码的字符串进行解码。\r\n");
      out.write("\t\t\t\t\treturnvalue=unescape(document.cookie.substring(sd, end))\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t  return returnvalue;\r\n");
      out.write("\t\t\t} \r\n");
      out.write("          \r\n");
      out.write("/*  \t\t\t function get_cookie(name) {\r\n");
      out.write(" \t\t\t\t   var cookies = document.cookie.split(\";\");\r\n");
      out.write(" \t\t\t\t   for(var i=0;i<cookies.length;i++) {\r\n");
      out.write(" \t\t\t\t    var cookie = cookies[i];\r\n");
      out.write(" \t\t\t\t    var cookieStr = cookie.split(\"=\");\r\n");
      out.write(" \t\t\t\t    if(cookieStr && cookieStr[0].trim()==name) {\r\n");
      out.write(" \t\t\t\t     return  decodeURI(cookieStr[1]);\r\n");
      out.write(" \t\t\t\t    }\r\n");
      out.write(" \t\t\t\t   }\r\n");
      out.write(" \t\t\t\t } */\r\n");
      out.write("         \r\n");
      out.write("          \r\n");
      out.write("          //确认删除点击事件\r\n");
      out.write("          var ADelete=document.getElementsByClassName('delete_topic');\r\n");
      out.write("          for(var i=0;i<ADelete.length;i++){\r\n");
      out.write("        \t  ADelete[i].onclick=function(){\r\n");
      out.write("        \t\t  return confirm('确认删除吗？');\r\n");
      out.write("        \t  } \r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("    \t  //签到动作\r\n");
      out.write("          var sign_d1=document.getElementById('sign_d1');\r\n");
      out.write("          var sign_d2=document.getElementById('sign_d2');\r\n");
      out.write("          var sign_span1=document.getElementById('sign_span1');\r\n");
      out.write("          var sign_span2=document.getElementById('sign_span2');\r\n");
      out.write("          var is_sign=document.getElementById('is_sign');\r\n");
      out.write("          if(is_sign.value=='false'){ //等于false说明还没有签到\r\n");
      out.write("\t          \tsign_d1.style.display='inline-block';\r\n");
      out.write("\t        \tsign_span1.style.display='inline-block';\r\n");
      out.write("\t        \tsign_d2.style.display='none';\r\n");
      out.write("\t        \tsign_span2.style.display='none';\r\n");
      out.write("\r\n");
      out.write("              sign_d1.onclick=function () {\r\n");
      out.write("            \t  \r\n");
      out.write("            \t  //判断用户是否已经登录！\r\n");
      out.write("            \t  var userid=document.getElementById('userid');\r\n");
      out.write("            \t  if(userid.value==''){\r\n");
      out.write("            \t\t  window.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/login.jsp\";\r\n");
      out.write("            \t\t  return;\r\n");
      out.write("            \t  }\r\n");
      out.write("            \t  \r\n");
      out.write("                    //创建ajax对象\r\n");
      out.write("                    var xhr=new XMLHttpRequest();\r\n");
      out.write("                    //连接服务器\r\n");
      out.write("                    xhr.open(\"get\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/signServlet.do\",true);\r\n");
      out.write("                    //发送\r\n");
      out.write("                    xhr.send();\r\n");
      out.write("                    //响应\r\n");
      out.write("                    xhr.onreadystatechange=function () {\r\n");
      out.write("                        if(xhr.readyState===4){\r\n");
      out.write("                            if(xhr.status===200){\r\n");
      out.write("                            \tvar temp=xhr.responseText;\r\n");
      out.write("                                //无论是true还是false应该都是今天已经签到成功了\r\n");
      out.write("                            \tsign_d1.style.display='none';\r\n");
      out.write("                            \tsign_span1.style.display='none';\r\n");
      out.write("                            \tsign_d2.style.display='inline-block';\r\n");
      out.write("                            \tsign_span2.style.display='inline-block';\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("          }else{\r\n");
      out.write("          \tsign_d1.style.display='none';\r\n");
      out.write("        \tsign_span1.style.display='none';\r\n");
      out.write("        \tsign_d2.style.display='inline-block';\r\n");
      out.write("        \tsign_span2.style.display='inline-block';\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          var weekAnswerTop=document.getElementById('weekAnswerTop');\r\n");
      out.write("          var kissNumList=document.getElementById('kissNumList');\r\n");
      out.write("          var hotViewList=document.getElementById('hotViewList');\r\n");
      out.write("          var hotReplyList=document.getElementById('hotReplyList');\r\n");
      out.write("          var top_none=document.getElementsByClassName('top_none');\r\n");
      out.write("          if(weekAnswerTop.innerHTML.trim()==''){\r\n");
      out.write("        \t  top_none[0].style.display='block';\r\n");
      out.write("          }\r\n");
      out.write("          if(kissNumList.innerHTML.trim()==''){\r\n");
      out.write("        \t  top_none[1].style.display='block';\r\n");
      out.write("          }\r\n");
      out.write("          var temp_hvl=hotViewList.getElementsByTagName('dd');\r\n");
      out.write("\t\t  if(temp_hvl.length==0){\r\n");
      out.write("\t\t\t  top_none[2].style.display='block';\r\n");
      out.write("          }\r\n");
      out.write("\t\t  var temp_htl=hotReplyList.getElementsByTagName('dd');\r\n");
      out.write("\t      if(temp_htl.length==0){\r\n");
      out.write("\t    \t  top_none[3].style.display='block';\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("        }\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- 将用户的签到信息放置在隐藏域中，用js来判断是否需要显示签到 -->\r\n");

	Userinfo user=(Userinfo)session.getAttribute("userInfo");
	String check="false";
	if(user!=null){
		boolean temp=TimeToStringUtil.checkStringTimeIsEqulas(user.getSignTime(), new Date());
		if(temp==true){
			check="true";
		}else{
			check="false";
		}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" id=\"is_sign\" value=\"");
      out.print(check);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" id=\"userid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 以下为各种排行榜 -->\r\n");
      out.write("<script id=\"wal\" type=\"text/html\">\r\n");
      out.write("\t  {{each $data as topicInfoEx index}}\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home/{{topicInfoEx.userId }}\">\r\n");
      out.write("            <img src=\"{{topicInfoEx.headUrl }}\">\r\n");
      out.write("            <cite>{{topicInfoEx.nickName }}</cite>\r\n");
      out.write("            <i>{{topicInfoEx.answerNum }}次回答</i>\r\n");
      out.write("          </a>\r\n");
      out.write("        </dd>\r\n");
      out.write("\t  {{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script id=\"knl\" type=\"text/html\">\r\n");
      out.write("\t  {{each $data as topicInfoEx index}}\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home/{{topicInfoEx.userId }}\">\r\n");
      out.write("            <img src=\"{{topicInfoEx.headUrl }}\">\r\n");
      out.write("            <cite>{{topicInfoEx.nickName }}</cite>\r\n");
      out.write("            <i>{{topicInfoEx.kissNum }}飞吻</i>\r\n");
      out.write("          </a>\r\n");
      out.write("        </dd>\r\n");
      out.write("\t  {{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script id=\"hvl\" type=\"text/html\">\r\n");
      out.write("\t  {{each $data as topicInfoEx index}}\r\n");
      out.write("      \t<dd>\r\n");
      out.write("        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/topicDetail.do?topicid={{topicInfoEx.id}}\">{{topicInfoEx.title}}</a>\r\n");
      out.write("        \t<span><i class=\"iconfont\">&#xe60b;</i> {{topicInfoEx.viewCount}}</span>\r\n");
      out.write("      \t</dd>\r\n");
      out.write("\t  {{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script id=\"hrl\" type=\"text/html\">\r\n");
      out.write("\t  {{each $data as topicInfoEx index}}\r\n");
      out.write("      \t<dd>\r\n");
      out.write("        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/topicDetail.do?topicid={{topicInfoEx.id}}\">{{topicInfoEx.title}}</a>\r\n");
      out.write("        \t<span><i class=\"iconfont\">&#xe60c;</i> {{topicInfoEx.answerNum}}</span>\r\n");
      out.write("      \t</dd>\r\n");
      out.write("\t  {{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("  <div class=\"main\">\r\n");
      out.write("    <a class=\"logo\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goIndex/all\" title=\"Fly\">Fly社区</a>\r\n");
      out.write("    <div class=\"nav\">\r\n");
      out.write("      <a class=\"nav-this\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goIndex/all\">\r\n");
      out.write("        <i class=\"iconfont icon-wenda\"></i>问答\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"http://www.layui.com/\" target=\"_blank\">\r\n");
      out.write("        <i class=\"iconfont icon-ui\"></i>框架\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"nav-user\">\r\n");
      out.write("    \r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <!-- 登入后的状态 -->\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"main layui-clear\">\r\n");
      out.write("  <div class=\"wrap\">\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("      <div class=\"fly-tab fly-tab-index\">\r\n");
      out.write("        <span>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goIndex/all\">全部</a>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goIndex/naccept\">未采纳</a>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goIndex/accept\">已采纳</a>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goIndex/nice\">精帖</a>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goIndex/mytopic\">我的帖</a>\r\n");
      out.write("        </span>\r\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goIndex/search\" class=\"fly-search\" method=\"get\">\r\n");
      out.write("          <i class=\"iconfont icon-sousuo\"></i>\r\n");
      out.write("          <input class=\"layui-input\" autocomplete=\"off\" placeholder=\"搜索内容，回车跳转\" type=\"text\" name=\"searchStr\">\r\n");
      out.write("        </form>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/loadOption.do\" class=\"layui-btn jie-add\">发布问题</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <!-- 顶置帖子 -->\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <!-- 新帖 新帖 新帖 新帖 新帖 新帖 新帖 新帖 新帖 新帖 新帖 -->\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f10(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("      ");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f11 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      _jspx_th_c_005fif_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f11.setParent(null);
      // /jsp/index.jsp(514,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f11.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty requestScope.topicList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f11 = _jspx_th_c_005fif_005f11.doStartTag();
      if (_jspx_eval_c_005fif_005f11 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<div style=\"text-align: center\">\r\n");
          out.write("\r\n");
          out.write("        \t");

        		String jumpTarget=(String)request.getAttribute("jumpTarget");
        		if(jumpTarget.equals("all")){
			
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"laypage-main\">\r\n");
          out.write("          \t\t\t<a id=\"moreTopic\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/jsp/index_fenye.jsp?target=all\" class=\"laypage-next\">更多求解</a>\r\n");
          out.write("        \t\t</div>\r\n");
          out.write("\t\t\t");

        		}else if(jumpTarget.equals("naccept")){
        	
          out.write("\r\n");
          out.write("        \t\t<div class=\"laypage-main\">\r\n");
          out.write("          \t\t\t<a id=\"moreTopic\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/jsp/index_fenye.jsp?target=naccept\" class=\"laypage-next\">更多求解</a>\r\n");
          out.write("        \t\t</div>\t\t\r\n");
          out.write("        \t");

        		}else if(jumpTarget.equals("accept")){
        	
          out.write("\t\t\r\n");
          out.write("        \t    <div class=\"laypage-main\">\r\n");
          out.write("          \t\t\t<a id=\"moreTopic\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/jsp/index_fenye.jsp?target=accept\" class=\"laypage-next\">更多求解</a>\r\n");
          out.write("        \t\t</div>\r\n");
          out.write("        \t");

        		}else if(jumpTarget.equals("nice")){
        	
          out.write("\t\r\n");
          out.write("        \t\t<div class=\"laypage-main\">\r\n");
          out.write("          \t\t\t<a id=\"moreTopic\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/jsp/index_fenye.jsp?target=nice\" class=\"laypage-next\">更多求解</a>\r\n");
          out.write("        \t\t</div>\r\n");
          out.write("        \t");

        		}else if(jumpTarget.equals("mytopic")){
        	
          out.write("\r\n");
          out.write("        \t\t<div class=\"laypage-main\">\r\n");
          out.write("          \t\t\t<a id=\"moreTopic\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/jsp/index_fenye.jsp?target=mytopic\" class=\"laypage-next\">更多求解</a>\r\n");
          out.write("        \t\t</div>\r\n");
          out.write("        \t");
		
        		}else if(jumpTarget.equals("search")){
        	
          out.write("\r\n");
          out.write("        \t\t<div class=\"laypage-main\">\r\n");
          out.write("          \t\t\t<a id=\"moreTopic\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/jsp/index_fenye.jsp?target=search&searchStr=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.searchStr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"laypage-next\">更多求解</a>\r\n");
          out.write("        \t\t</div>\r\n");
          out.write("        \t");

        		}
        	
          out.write("\r\n");
          out.write("      \t</div>\r\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f11.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f11);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f11);
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"edge\">\r\n");
      out.write("  \t<div style=\"position:relative;height:113px;\" class=\"fly-panel leifeng-rank\"> \r\n");
      out.write("      <!-- <h3 class=\"fly-panel-title\">近一月回答榜 - TOP 12</h3> -->\r\n");
      out.write("      <h3 class=\"fly-panel-title\">每日签到</h3>\r\n");
      out.write("      \t<div style=\"display:none; position:absolute;left:50px;top:66px;\" id=\"sign_d1\">今日签到</div>\r\n");
      out.write("      \t<span id=\"sign_span1\" style=\"display:none; position:absolute;left:164px;top:72px;\">今日还没有签到哦！</span>\r\n");
      out.write("        <div style=\"position:absolute;left:50px;top:66px;\" id=\"sign_d2\">今日已签到</div>\r\n");
      out.write("        <span id=\"sign_span2\" style=\"display:none; position:absolute;left:164px;top:72px;;\">获得了<span style=\"color:#ff5722;\"> 5 </span>飞吻</span>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"fly-panel leifeng-rank\"> \r\n");
      out.write("      <!-- <h3 class=\"fly-panel-title\">近一月回答榜 - TOP 12</h3> -->\r\n");
      out.write("      <h3 class=\"fly-panel-title\">本周回答榜  - TOP 8</h3>\r\n");
      out.write("      <p class=\"top_none\" style=\"display:none; color:#a9b7b7; text-align:center; position:relative; top:5px\" >暂无</p>\r\n");
      out.write("      <dl id=\"weekAnswerTop\">\r\n");
      out.write("      \r\n");
      out.write("      </dl>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"fly-panel leifeng-rank\"> \r\n");
      out.write("      <!-- <h3 class=\"fly-panel-title\">近一月回答榜 - TOP 12</h3> -->\r\n");
      out.write("      <h3 class=\"fly-panel-title\">飞吻排行榜  - TOP 4</h3>\r\n");
      out.write("      <dl id=\"kissNumList\">\r\n");
      out.write("      \r\n");
      out.write("\t  \r\n");
      out.write("      </dl>\r\n");
      out.write("      <p class=\"top_none\" style=\"display:none; color:#a9b7b7; text-align:center; position:relative; top:5px\" >暂无</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <dl id=\"hotViewList\" class=\"fly-panel fly-list-one\"> \r\n");
      out.write("      <dt  class=\"fly-panel-title\">近期热帖</dt>\r\n");
      out.write("\t  <p class=\"top_none\" style=\"display:none; color:#a9b7b7; text-align:center; position:relative; top:5px\" >暂无</p>\r\n");
      out.write("    </dl>\r\n");
      out.write("    \r\n");
      out.write("    <div > \r\n");
      out.write("    <dl id=\"hotReplyList\" class=\"fly-panel fly-list-one\"> \r\n");
      out.write("      <dt class=\"fly-panel-title\">近期热议</dt>\r\n");
      out.write("      <p class=\"top_none\" style=\"display:none; color:#a9b7b7; text-align:center; position:relative; top:5px\" >暂无</p>\r\n");
      out.write("    </dl>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"fly-panel fly-link\"> \r\n");
      out.write("      <h3 class=\"fly-panel-title\">友情链接</h3>\r\n");
      out.write("      <dl>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"http://www.layui.com/\" target=\"_blank\">layui</a>\r\n");
      out.write("        </dd>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"http://layim.layui.com/\" target=\"_blank\">LayIM</a>\r\n");
      out.write("        </dd>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"http://layer.layui.com/\" target=\"_blank\">layer</a>\r\n");
      out.write("        </dd>\r\n");
      out.write("      </dl>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("  <p><a href=\"http://fly.layui.com/\">Fly社区</a> 2017 &copy; <a href=\"http://www.layui.com/\">layui.com</a></p>\r\n");
      out.write("  <p>\r\n");
      out.write("    <a href=\"http://fly.layui.com/auth/get\" target=\"_blank\">产品授权</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/8157.html\" target=\"_blank\">获取Fly社区模版</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/2461.html\" target=\"_blank\">微信公众号</a>\r\n");
      out.write("  </p>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/layui/layui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("layui.cache.page = '';\r\n");
      out.write("layui.cache.user = {\r\n");
      out.write("  username: '游客'\r\n");
      out.write("  ,uid: -1\r\n");
      out.write("  ,avatar: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/images/avatar/00.jpg'  //老师说单引号的就不用改了\r\n");
      out.write("  ,experience: 83\r\n");
      out.write("  ,sex: '男'\r\n");
      out.write("};\r\n");
      out.write("layui.config({\r\n");
      out.write("  version: \"2.0.0\"\r\n");
      out.write("  ,base: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/mods/'\r\n");
      out.write("}).extend({\r\n");
      out.write("  fly: 'index'\r\n");
      out.write("}).use('fly');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /jsp/index.jsp(13,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope.topicList }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("   \t\t\t\t\t ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /jsp/index.jsp(21,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.topicList==null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("  \r\n");
        out.write("\t\t      \t\t");
        if (_jspx_meth_c_005fredirect_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t      \t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f0 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    _jspx_th_c_005fredirect_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fredirect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /jsp/index.jsp(22,10) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fredirect_005f0.setUrl("/goIndex/all");
    int _jspx_eval_c_005fredirect_005f0 = _jspx_th_c_005fredirect_005f0.doStartTag();
    if (_jspx_th_c_005fredirect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /jsp/index.jsp(338,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.userInfo }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("      \t<!-- 未登入状态 -->\r\n");
        out.write("     \t <a class=\"unlogin\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/jsp/login.jsp\"><i class=\"iconfont icon-touxiang\"></i></a>\r\n");
        out.write("      \t<span><a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/jsp/login.jsp\">登入</a><a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/jsp/reg.jsp\">注册</a></span>\r\n");
        out.write("      \t<p class=\"out-login\">\r\n");
        out.write("        <!-- <a href=\"\" onclick=\"layer.msg('正在通过QQ登入', {icon:16, shade: 0.1, time:0})\" class=\"iconfont icon-qq\" title=\"QQ登入\"></a>\r\n");
        out.write("        <a href=\"\" onclick=\"layer.msg('正在通过微博登入', {icon:16, shade: 0.1, time:0})\" class=\"iconfont icon-weibo\" title=\"微博登入\"></a> -->\r\n");
        out.write("        <a href=\"\" onclick=\"layer.msg('暂不支持！', {icon:16, shade: 0.1, time:0})\" class=\"iconfont icon-qq\" title=\"QQ登入\"></a>\r\n");
        out.write("        <a href=\"\" onclick=\"layer.msg('暂不支持！', {icon:16, shade: 0.1, time:0})\" class=\"iconfont icon-weibo\" title=\"微博登入\"></a>\r\n");
        out.write("      \t</p>   \r\n");
        out.write("      ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent(null);
    // /jsp/index.jsp(351,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.userInfo }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("      \t<a class=\"avatar\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/jsp/user/center.jsp\">\r\n");
        out.write("        <img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.headUrl }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("        <cite>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</cite>\r\n");
        out.write("      \t</a>\r\n");
        out.write("      \t<a style=\"display:inline-block; position:relative; top:-1px\" class=\"avatar\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/jsp/grade_list.jsp\"><i>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.grade }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</i> </a>\r\n");
        out.write("     \t<div class=\"nav\">\r\n");
        out.write("        <a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/jsp/user/set.jsp\"><i class=\"iconfont icon-shezhi\"></i>设置</a>\r\n");
        out.write("        <a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/logout.do\"><i class=\"iconfont icon-tuichu\" style=\"top: 0; font-size: 22px;\"></i>退了</a>\r\n");
        out.write("      </div>\r\n");
        out.write("      ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f4.setParent(null);
    // /jsp/index.jsp(388,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.topTopicList!=null && !empty requestScope.topTopicList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
    if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("      \t<ul class=\"fly-list fly-list-top\">\r\n");
        out.write("        ");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f4, _jspx_page_context))
          return true;
        out.write("\t\r\n");
        out.write("\t\t\r\n");
        out.write("\t\t");
        out.write("\r\n");
        out.write("      </ul>\r\n");
        out.write("      ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
    // /jsp/index.jsp(390,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/jsp/index.jsp(390,8) '${requestScope.topTopicList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${requestScope.topTopicList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /jsp/index.jsp(390,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("topTopicList");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- var -->\r\n");
          out.write("\t\t\t          <li class=\"fly-list-li\">\r\n");
          out.write("\t\t\t          <!-- <a href=\"user/home.html\" class=\"fly-list-avatar\"> -->\r\n");
          out.write("\t\t\t          <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/home/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topTopicList.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"fly-list-avatar\">\r\n");
          out.write("\t\t\t            <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topTopicList.headUrl }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"\">\r\n");
          out.write("\t\t\t          </a>\r\n");
          out.write("\t\t\t          <h2 class=\"fly-tip\">\r\n");
          out.write("\t\t\t            <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/topicDetail.do?topicid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topTopicList.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topTopicList.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\r\n");
          out.write("\t\t\t            <span class=\"fly-tip-stick\">置顶</span>\r\n");
          out.write("\r\n");
          out.write("            \t\t\t");
          if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t          </h2>\r\n");
          out.write("\t\t\t          <p>\r\n");
          out.write("\t\t\t            <span><a href=\"user/home.html\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topTopicList.nickName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></span>\r\n");
          out.write("\t\t\t            <span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topTopicList.createTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\t\t\t            <span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topTopicList.classname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\t\t\t            <!-- 编辑和删除帖子 -->\r\n");
          out.write("\t\t\t            ");
          if (_jspx_meth_c_005fif_005f6(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t            <span class=\"fly-list-hint\"> \r\n");
          out.write("\t\t\t              <i class=\"iconfont\" title=\"回答\">&#xe60c;</i> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topTopicList.commentCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("\t\t\t              <i class=\"iconfont\" title=\"人气\">&#xe60b;</i> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topTopicList.viewCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("\t\t\t            </span>\r\n");
          out.write("\t\t\t          </p>\r\n");
          out.write("\t\t\t          <form class=\"top_good_form\" action=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/editTopGoodServlet.do\" method=\"get\" style=\"position: absolute;left: 385px;top: 33px;\">\r\n");
          out.write("\t\t\t\t\t        ( 加精 <input type=\"checkbox\" value=\"good\" class=\"top_good\" name=\"topAndGood\">\r\n");
          out.write("\t\t\t\t\t        顶置 <input type=\"checkbox\" value=\"top\" class=\"top_good\" name=\"topAndGood\">\r\n");
          out.write("\t\t\t\t\t        <input type=\"hidden\" name=\"topicid\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topTopicList.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\r\n");
          out.write("\t\t\t\t\t        <input type=\"submit\" value=\"确定\"/> )\r\n");
          out.write("\t\t\t\t\t  </form>\r\n");
          out.write("\t\t\t        </li>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /jsp/index.jsp(400,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topTopicList.isGood==1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
    if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<span class=\"fly-tip-jing\">精帖</span>");
        int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /jsp/index.jsp(407,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.isManager==1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
    if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t            <a class='delete_topic' href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/deleteTopicServlet.do?topicid=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topTopicList.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" >删除</a>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
        out.write("\t\t\t\t\t\t    <span class='editor_topic' >编辑</span>\r\n");
        out.write("\t\t\t            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f7.setParent(null);
    // /jsp/index.jsp(468,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty requestScope.topicList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
    if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("      \t\t      <ul class=\"fly-list\">\r\n");
        out.write("   \t\t\t\t\r\n");
        out.write("\t\t        ");
        if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f7, _jspx_page_context))
          return true;
        out.write("\t\r\n");
        out.write("      </ul>\r\n");
        out.write("      ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f7, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f7);
    // /jsp/index.jsp(471,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/jsp/index.jsp(471,10) '${requestScope.topicList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${requestScope.topicList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /jsp/index.jsp(471,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("topicInfoEx");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t          <li class=\"fly-list-li\">\r\n");
          out.write("\t\t\t          <!-- <a href=\"user/home.html\" class=\"fly-list-avatar\"> -->\r\n");
          out.write("\t\t\t          <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/home/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topicInfoEx.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"fly-list-avatar\">\r\n");
          out.write("\t\t\t            <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topicInfoEx.headUrl }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"\">\r\n");
          out.write("\t\t\t          </a>\r\n");
          out.write("\t\t\t          <h2 class=\"fly-tip\">\r\n");
          out.write("\t\t\t            <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/topicDetail.do?topicid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topicInfoEx.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topicInfoEx.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\r\n");
          out.write("\t\t\t            ");
          if (_jspx_meth_c_005fif_005f8(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t\t          </h2>\r\n");
          out.write("\t\t\t          <p >\r\n");
          out.write("\t\t\t            <span><a href=\"user/home.html\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topicInfoEx.nickName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></span>\r\n");
          out.write("\t\t\t            <span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topicInfoEx.createTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\t\t\t            <span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topicInfoEx.classname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\t\t\t            <!-- 编辑和删除帖子 -->\r\n");
          out.write("\t\t\t            ");
          if (_jspx_meth_c_005fif_005f9(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t   \r\n");
          out.write("\t\t\t            <span class=\"fly-list-hint\"> \r\n");
          out.write("\t\t\t              <i class=\"iconfont\" title=\"回答\">&#xe60c;</i> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topicInfoEx.commentCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("\t\t\t              <i class=\"iconfont\" title=\"人气\">&#xe60b;</i> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topicInfoEx.viewCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("\t\t\t            </span>\r\n");
          out.write("\t\t\t          </p>\r\n");
          out.write("\t\t\t          \r\n");
          out.write("\t\t\t          <form class=\"top_good_form\" action=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/editTopGoodServlet.do\" method=\"get\" style=\"position: absolute;left: 385px;top: 33px;\">\r\n");
          out.write("\t\t\t\t\t        ( 加精 <input type=\"checkbox\" value=\"good\" class=\"top_good\" name=\"topAndGood\">\r\n");
          out.write("\t\t\t\t\t        顶置 <input type=\"checkbox\" value=\"top\" class=\"top_good\" name=\"topAndGood\">\r\n");
          out.write("\t\t\t\t\t        <input type=\"hidden\" name=\"topicid\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topicInfoEx.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\r\n");
          out.write("\t\t\t\t\t        <input type=\"submit\" value=\"确定\"/> )\r\n");
          out.write("\t\t\t\t\t  </form>\r\n");
          out.write("\t\t\t\t\t  \r\n");
          out.write("\t\t\t        </li>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /jsp/index.jsp(479,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topicInfoEx.isGood=='1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
    if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<span class=\"fly-tip-jing\">精帖</span>");
        int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f9 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f9.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /jsp/index.jsp(486,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f9.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.isManager==1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f9 = _jspx_th_c_005fif_005f9.doStartTag();
    if (_jspx_eval_c_005fif_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t            \t<a class='delete_topic' href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/deleteTopicServlet.do?topicid=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topicInfoEx.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">删除</a>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
        out.write("\t\t\t\t\t    \t<span class='editor_topic' >编辑</span>\r\n");
        out.write("\t\t\t            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f9.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f9);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f10 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f10.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f10.setParent(null);
    // /jsp/index.jsp(508,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f10.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope.topicList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f10 = _jspx_th_c_005fif_005f10.doStartTag();
    if (_jspx_eval_c_005fif_005f10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("      \t<br/>\r\n");
        out.write("      \t<h1 style=\"text-align:center;font-size:16px;\">呀 ! 没有找到你想要的帖子</h1>\r\n");
        out.write("      ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f10.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f10);
    return false;
  }
}
