/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2018-03-08 10:42:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_005ffenye_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/java_web_pro/yklgbbs/code/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/yklgbbs/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1517388735640L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>基于 layui 的极简社区页面模版</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("  <meta name=\"keywords\" content=\"fly,layui,前端社区\">\r\n");
      out.write("  <meta name=\"description\" content=\"Fly社区是模块化前端UI框架Layui的官网社区，致力于为web开发提供强劲动力\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/layui/css/layui.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/css/global.css\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- 首先需要引入css样式表 与 js -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/css/mricode.pagination.css\" rel=\"stylesheet\" type=\"text/css\" charset=\"utf-8\">\r\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/js/mricode.pagination.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/js/template-web.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 为编辑和删除帖子设置效果 -->\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("        .top_good_form{\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        .delete_topic,.editor_topic{\r\n");
      out.write("            color: black;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .delete_topic:hover,.editor_topic:hover{\r\n");
      out.write("            color: #3bc3e0;\r\n");
      out.write("            transition: 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .fly-list-li{\r\n");
      out.write("        \tposition: relative;\r\n");
      out.write("        }\r\n");
      out.write("   </style>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 下面为分页部分 -->\r\n");
      out.write("\t<!-- 注：下面完成的是Ajax刷新 -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\twindow.onload=function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//判断是否有top榜的cookie，如果没有则添加\r\n");
      out.write("\t       \tif(get_cookie('weekAnswerList')==''){\r\n");
      out.write("\t       \t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/add_cookie.jsp?check=1\";\r\n");
      out.write("\t       \t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* \r\n");
      out.write("\t\t\t\t注：只有进入到index才会获取到下面的这些cookie，否则在本页面和detail页面不能正常显示\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t\t\r\n");
      out.write("        \t//将json字符串渲染到指定模板中\r\n");
      out.write("        \t//1：本周top回答渲染 与 将weekAnswerList存入cookie\r\n");
      out.write("\t\t\t//var str1='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.weekAnswerList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'; //此时的str1为字符串\r\n");
      out.write("        \t//document.cookie='weekAnswerList='+str1+';Path=/';\r\n");
      out.write("        \tvar str1=get_cookie('weekAnswerList');\r\n");
      out.write("\t\t\tvar json1=JSON.parse(str1);\r\n");
      out.write("\t\t\tvar html1=template('wal',json1);\r\n");
      out.write("\t\t\tdocument.getElementById('weekAnswerTop').innerHTML=html1;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//2：飞吻数前8榜渲染 与 将hotViewList存入cookie\r\n");
      out.write("\t\t\t//var str2='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.kissNumList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'; //此时的str1为字符串\r\n");
      out.write("        \t//document.cookie='kissNumList='+str2+';Path=/';\r\n");
      out.write("        \tvar str2=get_cookie('kissNumList');\r\n");
      out.write("\t\t\tvar json2=JSON.parse(str2);\r\n");
      out.write("\t\t\tvar html2=template('knl',json2);\r\n");
      out.write("\t\t\tdocument.getElementById('kissNumList').innerHTML=html2;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//3：10天内热视渲染 与 将hotViewList存入cookie\r\n");
      out.write("\t\t\t//var str3='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.hotViewList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'; //此时的str1为字符串\r\n");
      out.write("        \t//document.cookie='hotViewList='+str3+';Path=/';\r\n");
      out.write("        \tvar str3=get_cookie('hotViewList');\r\n");
      out.write("\t\t\tvar json3=JSON.parse(str3);\r\n");
      out.write("\t\t\tvar html3=template('hvl',json3);\r\n");
      out.write("\t\t\tdocument.getElementById('hotViewList').innerHTML+=html3;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//4：10天内热答渲染 与 将hotReplyList存入cookie\r\n");
      out.write("        \t//var str4='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.hotReplyList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'; //此时的str1为字符串\r\n");
      out.write("        \t//document.cookie='hotReplyList='+str4+';Path=/';\r\n");
      out.write("        \tvar str4=get_cookie('hotReplyList');\r\n");
      out.write("\t\t\tvar json4=JSON.parse(str4);\r\n");
      out.write("\t\t\tvar html4=template('hrl',json4);\r\n");
      out.write("\t\t\tdocument.getElementById('hotReplyList').innerHTML+=html4;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(get_cookie('jumpToAll')=='yes'){\r\n");
      out.write("\t\t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/index_fenye.jsp?target=all\";\r\n");
      out.write("\t\t\t\tdocument.cookie='jumpToAll=no;Path=/';\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//分析判断用户访问index_fenye.jsp的方式\r\n");
      out.write("\t\t\tvar pageNum;\r\n");
      out.write("\t\t\tif(get_cookie('pageNum')!=''){ //用户通过index.jsp页面进入index_fenye.jsp，或点击了页码后直接访问的index_fenye.jsp\r\n");
      out.write("\t\t\t\tpageNum=get_cookie('pageNum');\r\n");
      out.write("\t\t\t}else{ //用户直接进入index_fenye.jsp\r\n");
      out.write("\t\t\t\tvar pageNum=0;  //如果用户直接访问的index_fenye.jsp,就从第1页开始\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("            \r\n");
      out.write("\t\t\t//这里就是ajax生成局部页面的内容\r\n");
      out.write("\t\t\t$(\"#page_fenye\").pagination({ \r\n");
      out.write("\t\t\t\tpageIndex:pageNum, //从pageIndex+1页开始显示（重要）\r\n");
      out.write("\t\t\t\tpageSize:10, //分页后每页显示10条数据\r\n");
      out.write("\t\t\t\tpageBtnCount:9, //按钮个数，包括上下页，首尾页\r\n");
      out.write("\t\t\t\tshowFirstLastBtn:true, //是否显示首页，尾页按钮\r\n");
      out.write("\t\t\t\tfirstBtnText:\"首页\", //这里可以设置个性显示内容\r\n");
      out.write("\t\t\t\tlastBtnText:\"尾页\",\r\n");
      out.write("\t\t\t\tprevBtnText:\"上一页\",\r\n");
      out.write("\t\t\t\tnextBtnText:\"下一页\",\r\n");
      out.write("\t\t\t\tremote:{\r\n");
      out.write("\t\t\t\t\t//每次点击按钮提交到处理请求的Servlet\r\n");
      out.write("\t\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/fenyeServlet.do?target=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.target}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&searchStr=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.searchStr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', \r\n");
      out.write("\t\t\t\t\tsuccess:function(data){ //注：data为：json字符串通过转换为了json对象\r\n");
      out.write("\t\t\t\t\t\tif(data.check=='notLogin'){\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/login.jsp\";\r\n");
      out.write("\t\t\t\t\t\t}else if(data.check=='jumpAll'){\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/index_fenye.jsp?target=all\";\r\n");
      out.write("\t\t\t\t\t\t}else if(data.check=='404'){\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/404.jsp\";\r\n");
      out.write("\t\t\t\t\t\t}else if(data.check=='noSearchStr'){\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/tips.jsp?tips=输入点内容再搜索吧！\";\r\n");
      out.write("\t\t\t\t\t\t}else if(data.total==0){\r\n");
      out.write("\t\t\t\t\t\t\tvar content_fenye=document.getElementById('content_fenye');\r\n");
      out.write("\t\t\t\t\t\t\tcontent_fenye.style.display='none';\r\n");
      out.write("\t\t\t\t\t\t\tvar noTopic=document.getElementById('noTopic');\r\n");
      out.write("\t\t\t\t\t\t\tnoTopic.style.display='block';\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tvar html=template('test_fenye',data); //date渲染到test模板中\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('content_fenye').innerHTML=html;\r\n");
      out.write("\t\t\t\t\t\t\tupEditorButton(); //重要：为每个帖子的编辑设置点击事件\r\n");
      out.write("\t\t\t\t\t\t\tconfirmDelete(); //为每个删除设置确认删除\r\n");
      out.write("\t\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//设置页码（a标签）的点击事件\r\n");
      out.write("            var OPageFenye=document.getElementById('page_fenye'); \r\n");
      out.write("\t\t\tOPageFenye.onclick=function () { //这里应用了冒泡事件，直接点击的其实不是OPageFenye，而是其中的a标签\r\n");
      out.write("\t\t    var pageIndex=$(\"#page_fenye\").pagination('getPageIndex'); //获取当前码，前用户查看帖子详情后，\r\n");
      out.write("\t\t            \t\t\t\t\t\t\t\t\t\t\t\t\t\t   //点击浏览器的返回，返回的依然是原来的index\r\n");
      out.write("\t\t    document.cookie='pageNum='+pageIndex+';Path=/';\r\n");
      out.write("\t\t    //注：下面的可能是兼容写法\r\n");
      out.write("\t\t    document.body.scrollTop = document.documentElement.scrollTop = 0; //js实现点击返回页面顶部\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t//获取js中的cookie的方法\r\n");
      out.write("\t\t\tfunction get_cookie(Name) { \r\n");
      out.write("\t\t\t\tvar search = Name + \"=\"//查询检索的值\r\n");
      out.write("\t\t\t\tvar returnvalue = \"\";//返回值\r\n");
      out.write("\t\t\t\tif (document.cookie.length > 0) {\r\n");
      out.write("\t\t\t\tsd = document.cookie.indexOf(search);\r\n");
      out.write("\t\t\t\t\tif (sd!= -1) {\r\n");
      out.write("\t\t\t\t\tsd += search.length;\r\n");
      out.write("\t\t\t\t\tend = document.cookie.indexOf(\";\", sd);\r\n");
      out.write("\t\t\t\t\tif (end == -1)\r\n");
      out.write("\t\t\t\t\tend = document.cookie.length;\r\n");
      out.write("\t\t\t    \t//unescape() 函数可对通过 escape() 编码的字符串进行解码。\r\n");
      out.write("\t\t\t\t\treturnvalue=unescape(document.cookie.substring(sd, end))\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t return returnvalue;\t   \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction upEditorButton() {\r\n");
      out.write("                //为编辑帖子设置点击事件\r\n");
      out.write("                var AEditor=document.getElementsByClassName('editor_topic');\r\n");
      out.write("                var ATopGoodForm=document.getElementsByClassName('top_good_form');\r\n");
      out.write("\r\n");
      out.write("                for(var i=0;i<AEditor.length;i++){\r\n");
      out.write("                    AEditor[i].showForm=i;\r\n");
      out.write("                    AEditor[i].OnOff=false;\r\n");
      out.write("                    AEditor[i].onclick=function () {\r\n");
      out.write("                        if(this.OnOff===false){\r\n");
      out.write("                            ATopGoodForm[this.showForm].style.display='inline-block';\r\n");
      out.write("                        }else{\r\n");
      out.write("                            ATopGoodForm[this.showForm].style.display='none';\r\n");
      out.write("                        }\r\n");
      out.write("                        this.OnOff=!this.OnOff;\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//确认删除点击事件\r\n");
      out.write("\t        function confirmDelete(){\r\n");
      out.write("\t        \t  var ADelete=document.getElementsByClassName('delete_topic');\r\n");
      out.write("\t\t          for(var i=0;i<ADelete.length;i++){\r\n");
      out.write("\t\t        \t  ADelete[i].onclick=function(){\r\n");
      out.write("\t\t        \t\t  return confirm('确认删除吗？');\r\n");
      out.write("\t\t        \t  } \r\n");
      out.write("\t\t          }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//每次点击分页jsp中的跳转套其他类型的帖子，就要重新设置一下页码\r\n");
      out.write("\t\t\tvar AA=document.getElementsByClassName('jump_to_target');\r\n");
      out.write("\t\t\tfor(var i=0;i<AA.length;i++){\r\n");
      out.write("\t\t\t\tAA[i].onclick=function(){\r\n");
      out.write("\t\t\t\t\tdocument.cookie='pageNum=0;Path=/';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//这个是搜索点击动作\r\n");
      out.write("\t\t\tvar OForm=document.getElementsByClassName('fly-search')[0];\r\n");
      out.write("\t\t\tvar OLayuiInput=document.getElementsByClassName('layui-input')[0];\r\n");
      out.write("\t\t\tOForm.onclick=function(){\r\n");
      out.write("\t\t\t\tif(OLayuiInput.value!=''){\r\n");
      out.write("\t\t\t\t\tdocument.cookie='pageNum=0;Path=/';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t          var weekAnswerTop=document.getElementById('weekAnswerTop');\r\n");
      out.write("\t          var kissNumList=document.getElementById('kissNumList');\r\n");
      out.write("\t          var hotViewList=document.getElementById('hotViewList');\r\n");
      out.write("\t          var hotReplyList=document.getElementById('hotReplyList');\r\n");
      out.write("\t          var top_none=document.getElementsByClassName('top_none');\r\n");
      out.write("\t          if(weekAnswerTop.innerHTML.trim()==''){\r\n");
      out.write("\t        \t  top_none[0].style.display='block';\r\n");
      out.write("\t          }\r\n");
      out.write("\t          if(kissNumList.innerHTML.trim()==''){\r\n");
      out.write("\t        \t  top_none[1].style.display='block';\r\n");
      out.write("\t          }\r\n");
      out.write("\t          var temp_hvl=hotViewList.getElementsByTagName('dd');\r\n");
      out.write("\t\t\t  if(temp_hvl.length==0){\r\n");
      out.write("\t\t\t\t  top_none[2].style.display='block';\r\n");
      out.write("\t          }\r\n");
      out.write("\t\t\t  var temp_htl=hotReplyList.getElementsByTagName('dd');\r\n");
      out.write("\t\t      if(temp_htl.length==0){\r\n");
      out.write("\t\t    \t  top_none[3].style.display='block';\r\n");
      out.write("\t          }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- 以下为各种排行榜 -->\t\r\n");
      out.write("\r\n");
      out.write("<script id=\"wal\" type=\"text/html\">\r\n");
      out.write("\t  {{each $data as topicInfoEx index}}\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home/{{topicInfoEx.userId }}\">\r\n");
      out.write("            <img src=\"{{topicInfoEx.headUrl }}\">\r\n");
      out.write("            <cite>{{topicInfoEx.nickName }}</cite>\r\n");
      out.write("            <i>{{topicInfoEx.answerNum }}次回答</i>\r\n");
      out.write("          </a>\r\n");
      out.write("        </dd>\r\n");
      out.write("\t  {{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script id=\"knl\" type=\"text/html\">\r\n");
      out.write("\t  {{each $data as topicInfoEx index}}\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home/{{topicInfoEx.userId }}\">\r\n");
      out.write("            <img src=\"{{topicInfoEx.headUrl }}\">\r\n");
      out.write("            <cite>{{topicInfoEx.nickName }}</cite>\r\n");
      out.write("            <i>{{topicInfoEx.kissNum }}飞吻</i>\r\n");
      out.write("          </a>\r\n");
      out.write("        </dd>\r\n");
      out.write("\t  {{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script id=\"hvl\" type=\"text/html\">\r\n");
      out.write("\t  {{each $data as topicInfoEx index}}\r\n");
      out.write("      \t<dd>\r\n");
      out.write("        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/topicDetail.do?topicid={{topicInfoEx.id}}\">{{topicInfoEx.title}}</a>\r\n");
      out.write("        \t<span><i class=\"iconfont\">&#xe60b;</i> {{topicInfoEx.viewCount}}</span>\r\n");
      out.write("      \t</dd>\r\n");
      out.write("\t  {{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script id=\"hrl\" type=\"text/html\">\r\n");
      out.write("\t  {{each $data as topicInfoEx index}}\r\n");
      out.write("      \t<dd>\r\n");
      out.write("        \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/topicDetail.do?topicid={{topicInfoEx.id}}\">{{topicInfoEx.title}}</a>\r\n");
      out.write("        \t<span><i class=\"iconfont\">&#xe60c;</i> {{topicInfoEx.answerNum}}</span>\r\n");
      out.write("      \t</dd>\r\n");
      out.write("\t  {{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("  <div class=\"main\">\r\n");
      out.write("    <a class=\"logo\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goIndex/all\" title=\"Fly\">Fly社区</a>\r\n");
      out.write("    <div class=\"nav\">\r\n");
      out.write("      <a class=\"nav-this\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goIndex/all\">\r\n");
      out.write("        <i class=\"iconfont icon-wenda\"></i>问答\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"http://www.layui.com/\" target=\"_blank\">\r\n");
      out.write("        <i class=\"iconfont icon-ui\"></i>框架\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"nav-user\">\r\n");
      out.write("    \r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <!-- 登入后的状态 -->\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"main layui-clear\">\r\n");
      out.write("  <div class=\"wrap\">\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("      <div class=\"fly-tab fly-tab-index\">\r\n");
      out.write("        <span>\r\n");
      out.write("          <a class=\"jump_to_target\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/index_fenye.jsp?target=all\">全部</a>\r\n");
      out.write("          <a class=\"jump_to_target\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/index_fenye.jsp?target=naccept\">未采纳</a>\r\n");
      out.write("          <a class=\"jump_to_target\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/index_fenye.jsp?target=accept\">已采纳</a>\r\n");
      out.write("          <a class=\"jump_to_target\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/index_fenye.jsp?target=nice\">精帖</a>\r\n");
      out.write("          <a class=\"jump_to_target\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/index_fenye.jsp?target=mytopic\">我的帖</a>\r\n");
      out.write("        </span>\r\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/index_fenye.jsp?target=search\" class=\"fly-search\" method=\"post\">\r\n");
      out.write("          <i class=\"iconfont icon-sousuo\"></i>\r\n");
      out.write("          <input class=\"layui-input\" autocomplete=\"off\" placeholder=\"搜索内容，回车跳转\" type=\"text\" name=\"searchStr\">\r\n");
      out.write("        </form>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/loadOption.do\" class=\"layui-btn jie-add\">发布问题</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <!-- 顶置帖子 -->\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <!-- 新帖 新帖 新帖 新帖 新帖 新帖 新帖 新帖 新帖 新帖 新帖 -->\r\n");
      out.write("      <!-- 数据内容显示块 -->\r\n");
      out.write("      <ul class=\"fly-list\" id=\"content_fenye\">\r\n");
      out.write("              \r\n");
      out.write("      </ul>\r\n");
      out.write("      \r\n");
      out.write("      <div id=\"noTopic\" style=\"display:none;\">\r\n");
      out.write("      \t<br/>\r\n");
      out.write("      \t<h1 style=\"text-align:center;font-size:16px;\">呀 ! 没有找到你想要的帖子</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <!-- 分页页码  下面的class去掉貌似也没什么问题-->\r\n");
      out.write("\t  <!-- <div id=\"page_fenye\" class=\"m-pagination\"></div> -->\r\n");
      out.write("\t  <div id=\"page_fenye\" class=\"m-pagination\" ></div>\r\n");
      out.write("      \r\n");
      out.write("\t\t<script id=\"test_fenye\" type=\"text/html\"> \r\n");
      out.write("\t\t{{ each list as topicInfoEx i}}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t  <li class=\"fly-list-li\">\r\n");
      out.write("\t\t\t          <!-- <a href=\"user/home.html\" class=\"fly-list-avatar\"> -->\r\n");
      out.write("\t\t\t          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home/{{topicInfoEx.userId}}\" class=\"fly-list-avatar\">\r\n");
      out.write("\t\t\t            <img src=\"{{topicInfoEx.headUrl}}\" alt=\"\">\r\n");
      out.write("\t\t\t          </a>\r\n");
      out.write("\t\t\t          <h2 class=\"fly-tip\">\r\n");
      out.write("\t\t\t            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/topicDetail.do?topicid={{topicInfoEx.id}}\">{{topicInfoEx.title}}</a>\r\n");
      out.write("\t\t\t\t\t\t{{if topicInfoEx.isGood==1 }}  \r\n");
      out.write("\t\t\t\t\t\t<span class=\"fly-tip-jing\">精帖</span>\r\n");
      out.write("\t\t\t\t\t\t{{/if}}\r\n");
      out.write("\t\t\t          </h2>\r\n");
      out.write("\t\t\t          <p>\r\n");
      out.write("\t\t\t            <span><a href=\"user/home.html\">{{topicInfoEx.nickName}}</a></span>\r\n");
      out.write("\t\t\t            <span>{{topicInfoEx.createTime}}</span>\r\n");
      out.write("\t\t\t            <span>{{topicInfoEx.classname}}</span>\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t            <span class=\"fly-list-hint\"> \r\n");
      out.write("\t\t\t              <i class=\"iconfont\" title=\"回答\">&#xe60c;</i> {{topicInfoEx.commentCount}}\r\n");
      out.write("\t\t\t              <i class=\"iconfont\" title=\"人气\">&#xe60b;</i> {{topicInfoEx.viewCount}}\r\n");
      out.write("\t\t\t            </span>\r\n");
      out.write("\t\t\t          </p>\r\n");
      out.write("\t\t\t\t\t\t<form class=\"top_good_form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/editTopGoodServlet.do\" method=\"get\" style=\"position: absolute;left: 385px;top: 33px;\">\r\n");
      out.write("\t\t\t\t\t        ( 加精 <input type=\"checkbox\" value=\"good\" class=\"top_good\" name=\"topAndGood\">\r\n");
      out.write("\t\t\t\t\t                    顶置 <input type=\"checkbox\" value=\"top\" class=\"top_good\" name=\"topAndGood\">\r\n");
      out.write("\t\t\t\t\t        <input type=\"hidden\" name=\"topicid\" value=\"{{topicInfoEx.id}}\"/>\r\n");
      out.write("\t\t\t\t\t        <input type=\"submit\" value=\"确定\"/> )\r\n");
      out.write("\t\t\t\t\t    </form>\r\n");
      out.write("\t\t\t          </li>\r\n");
      out.write("\t\t{{ /each}}\r\n");
      out.write("\t\t              \r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\r\n");
      out.write("      \r\n");
      out.write("<!--       <div style=\"text-align: center\">\r\n");
      out.write("        <div class=\"laypage-main\">\r\n");
      out.write("          <a href=\"jie/index.html\" class=\"laypage-next\">更多求解</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div> -->\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"edge\">\r\n");
      out.write("    <div class=\"fly-panel leifeng-rank\"> \r\n");
      out.write("      <!-- <h3 class=\"fly-panel-title\">近一月回答榜 - TOP 12</h3> -->\r\n");
      out.write("      <h3 class=\"fly-panel-title\">本周回答榜  - TOP 8</h3>\r\n");
      out.write("      <p class=\"top_none\" style=\"display:none; color:#a9b7b7; text-align:center; position:relative; top:5px\" >暂无</p>\r\n");
      out.write("      <dl id=\"weekAnswerTop\">\r\n");
      out.write("      \r\n");
      out.write("      </dl>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"fly-panel leifeng-rank\"> \r\n");
      out.write("      <!-- <h3 class=\"fly-panel-title\">近一月回答榜 - TOP 12</h3> -->\r\n");
      out.write("      <h3 class=\"fly-panel-title\">飞吻排行榜  - TOP 4</h3>\r\n");
      out.write("      <dl id=\"kissNumList\">\r\n");
      out.write("      \r\n");
      out.write("\t  \r\n");
      out.write("      </dl>\r\n");
      out.write("      <p class=\"top_none\" style=\"display:none; color:#a9b7b7; text-align:center; position:relative; top:5px\" >暂无</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <dl id=\"hotViewList\" class=\"fly-panel fly-list-one\"> \r\n");
      out.write("      <dt  class=\"fly-panel-title\">近期热帖</dt>\r\n");
      out.write("\t  <p class=\"top_none\" style=\"display:none; color:#a9b7b7; text-align:center; position:relative; top:5px\" >暂无</p>\r\n");
      out.write("    </dl>\r\n");
      out.write("    \r\n");
      out.write("    <div > \r\n");
      out.write("    <dl id=\"hotReplyList\" class=\"fly-panel fly-list-one\"> \r\n");
      out.write("      <dt class=\"fly-panel-title\">近期热议</dt>\r\n");
      out.write("      <p class=\"top_none\" style=\"display:none; color:#a9b7b7; text-align:center; position:relative; top:5px\" >暂无</p>\r\n");
      out.write("    </dl>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"fly-panel fly-link\"> \r\n");
      out.write("      <h3 class=\"fly-panel-title\">友情链接</h3>\r\n");
      out.write("      <dl>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"http://www.layui.com/\" target=\"_blank\">layui</a>\r\n");
      out.write("        </dd>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"http://layim.layui.com/\" target=\"_blank\">LayIM</a>\r\n");
      out.write("        </dd>\r\n");
      out.write("        <dd>\r\n");
      out.write("          <a href=\"http://layer.layui.com/\" target=\"_blank\">layer</a>\r\n");
      out.write("        </dd>\r\n");
      out.write("      </dl>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("  <p><a href=\"http://fly.layui.com/\">Fly社区</a> 2017 &copy; <a href=\"http://www.layui.com/\">layui.com</a></p>\r\n");
      out.write("  <p>\r\n");
      out.write("    <a href=\"http://fly.layui.com/auth/get\" target=\"_blank\">产品授权</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/8157.html\" target=\"_blank\">获取Fly社区模版</a>\r\n");
      out.write("    <a href=\"http://fly.layui.com/jie/2461.html\" target=\"_blank\">微信公众号</a>\r\n");
      out.write("  </p>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/layui/layui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("layui.cache.page = '';\r\n");
      out.write("layui.cache.user = {\r\n");
      out.write("  username: '游客'\r\n");
      out.write("  ,uid: -1\r\n");
      out.write("  ,avatar: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/images/avatar/00.jpg'  //老师说单引号的就不用改了\r\n");
      out.write("  ,experience: 83\r\n");
      out.write("  ,sex: '男'\r\n");
      out.write("};\r\n");
      out.write("layui.config({\r\n");
      out.write("  version: \"2.0.0\"\r\n");
      out.write("  ,base: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/res/mods/'\r\n");
      out.write("}).extend({\r\n");
      out.write("  fly: 'index'\r\n");
      out.write("}).use('fly');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /jsp/index_fenye.jsp(305,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.userInfo }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("      \t<!-- 未登入状态 -->\r\n");
        out.write("     \t <a class=\"unlogin\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/jsp/login.jsp\"><i class=\"iconfont icon-touxiang\"></i></a>\r\n");
        out.write("      \t<span><a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/jsp/login.jsp\">登入</a><a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/jsp/reg.jsp\">注册</a></span>\r\n");
        out.write("      \t<p class=\"out-login\">\r\n");
        out.write("        <a href=\"\" onclick=\"layer.msg('正在通过QQ登入', {icon:16, shade: 0.1, time:0})\" class=\"iconfont icon-qq\" title=\"QQ登入\"></a>\r\n");
        out.write("        <a href=\"\" onclick=\"layer.msg('正在通过微博登入', {icon:16, shade: 0.1, time:0})\" class=\"iconfont icon-weibo\" title=\"微博登入\"></a>\r\n");
        out.write("      \t</p>   \r\n");
        out.write("      ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /jsp/index_fenye.jsp(316,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.userInfo }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("      \t<a class=\"avatar\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/jsp/user/center.jsp\">\r\n");
        out.write("        <img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.headUrl }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("        <cite>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</cite>\r\n");
        out.write("      \t</a>\r\n");
        out.write("      \t<a style=\"display:inline-block; position:relative; top:-1px\" class=\"avatar\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/jsp/grade_list.jsp\"><i>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.grade }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</i> </a>\r\n");
        out.write("     \t<div class=\"nav\">\r\n");
        out.write("        <a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/jsp/user/set.jsp\"><i class=\"iconfont icon-shezhi\"></i>设置</a>\r\n");
        out.write("        <a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/logout.do\"><i class=\"iconfont icon-tuichu\" style=\"top: 0; font-size: 22px;\"></i>退了</a>\r\n");
        out.write("      </div>\r\n");
        out.write("      ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /jsp/index_fenye.jsp(416,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.isManager==1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t<a class='delete_topic' href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/deleteTopicServlet.do?topicid={{topicInfoEx.id}}\">删除</a>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
        out.write("\t\t\t\t\t   \t\t<span class='editor_topic'>编辑</span>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }
}
